we create a protocol and a struct wich it bring us data
JonathanAmador12/PokedexV2 pull request #1
Opened 2022-10-11 22:18 UTC by JonathanAmador12

2022-10-11 22:40 UTC, AmadorHeE requested changes

2022-10-11 22:40 UTC, AmadorHeE commented on PokedexV2/Networking/APIError.swift
> +    case noAutorize
It should be 'unauthorized'

2022-10-11 22:40 UTC, AmadorHeE commented on PokedexV2/Networking/HTTPRequestData.swift
> +// we need to create athother extension for we can implement a fucion like a astract funcion
Change this.

2022-10-12 00:15 UTC, JonathanAmador12 commented on PokedexV2/Networking/APIError.swift
> +    case noAutorize
fixed

2022-10-12 00:16 UTC, JonathanAmador12 commented on PokedexV2/Networking/HTTPRequestData.swift
> +// we need to create athother extension for we can implement a fucion like a astract funcion
fixed

2022-10-12 00:22 UTC, AmadorHeE approved these changes

2022-10-12 00:23 UTC, merged